# -----------------------------------------------------------------------------
# Конфигурация Telescan
# -----------------------------------------------------------------------------

[logging]
# Уровень логирования для консоли. Возможные значения: CRITICAL, ERROR, WARNING, INFO, DEBUG.
level = "INFO"

[check]
# Путь к JSON файлу с Telethon API ключами (api_id/api_hash).
apis = "./config/api_keys.json"
# Необязательный путь к файлу со списком прокси (один адрес на строку).
proxies = "./config/proxies.txt"
# Стратегия выбора прокси: round, random или sticky.
proxy_strategy = "round"
# Количество одновременных проверок сессий.
concurrency = 20
# Максимальное число повторов запроса при ошибках.
max_attempts = 3
# Таймаут установления соединения в секундах.
connect_timeout = 20
# Основание экспоненциального backoff при повторах.
backoff_base = 1.7
# Пауза между сетевыми запросами в секундах.
rate_delay = 0.3
# Путь к основному CSV отчёту о проверке.
out = "./reports/report.csv"
# Включить «сухой» режим без сетевых запросов.
dry_run = false

# Папка для сохранения .session файлов, полученных из tdata.
convert_out = "./converted_sessions"
# Таймаут конвертации одного tdata набора в секундах.
convert_timeout = 60
# Максимальное количество параллельных конвертаций tdata.
convert_parallel = 2
# Сохранять временные копии tdata после конвертации.
keep_temp = false
# Каталог с множеством поддиректорий tdata (необязательный).
# tdata_root = "./data/tdata"
# Каталог с .session файлами, добавляемый к проверке (необязательный).
# session_dir = "./data/sessions"

[convert]
# Директория для результатов конвертации (будет создана при необходимости).
output = "./converted"
# Таймаут обработки одного входного файла или каталога в секундах.
timeout = 60
# Количество параллельных задач при конвертации.
parallel = 4
# Сохранять промежуточные tdata директории после конвертации.
keep_temp = false
# Путь к JSON файлу с Telethon API ключами (обязателен для режима session→tdata).
apis = "./config/api_keys.json"
